import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,Search,ShoppingBag,Sparkles,Shirt,Cpu,Utensils,Palette,User,X,Upload,Check,LogOut} from 'lucide-react';

type Product={name:string;category:string;price:string;emoji:string};
const cats=[['Fashion','Virtual try-on ready',Shirt],['Custom Print','Create your own',Palette],['Electronics','Tech essentials',Cpu],['Food','Taste & enjoy',Utensils]] as const;
const products:Product[]=[
{name:'Essential Oversize Tee',category:'Fashion',price:'Rp 89.000',emoji:'👕'},
{name:'Custom DTF T-Shirt',category:'Custom Print',price:'Mulai Rp 65.000',emoji:'🎨'},
{name:'Urban Hoodie',category:'Fashion',price:'Rp 189.000',emoji:'🧥'},
{name:'Wireless Headphones',category:'Electronics',price:'Rp 249.000',emoji:'🎧'},
{name:'Smart Watch',category:'Electronics',price:'Rp 329.000',emoji:'⌚'},
{name:'Coffee & Croissant',category:'Food',price:'Rp 28.000',emoji:'🥐'}];

export default function App(){
 const[cat,setCat]=useState('All'),[q,setQ]=useState(''),[cart,setCart]=useState(0);
 const[auth,setAuth]=useState(false),[authMode,setAuthMode]=useState<'login'|'signup'>('login'),[authOpen,setAuthOpen]=useState(false);
 const[email,setEmail]=useState(''),[name,setName]=useState(''),[studio,setStudio]=useState(false),[garment,setGarment]=useState('T-Shirt');
 const[design,setDesign]=useState<string|null>(null),[toast,setToast]=useState(''); const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const saved=localStorage.getItem('after-user');if(saved){setAuth(true);setName(saved)}else{const t=setTimeout(()=>setAuthOpen(true),20000);return()=>clearTimeout(t)}},[]);
 const shown=useMemo(()=>products.filter(p=>(cat==='All'||p.category===cat)&&p.name.toLowerCase().includes(q.toLowerCase())),[cat,q]);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 const submitAuth=(e:React.FormEvent)=>{e.preventDefault();const who=(name||email.split('@')[0]||'Member');localStorage.setItem('after-user',who);setName(who);setAuth(true);setAuthOpen(false);notify('Welcome to AFTER AI, '+who+'!')};
 const logout=()=>{localStorage.removeItem('after-user');setAuth(false);setName('');notify('You are signed out')};
 const upload=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f){setDesign(URL.createObjectURL(f));notify('Design uploaded')}};
 const add=(p:Product)=>{setCart(v=>v+1);notify(p.name+' added to cart')};
 return <><header><a className="brand" href="#"><Sparkles/> AFTER <b>AI</b></a><nav><a href="#shop">Shop</a><a href="#studio">Virtual Studio</a><a href="#categories">Categories</a></nav><div className="headActions">{auth?<button className="userBtn" onClick={logout}><User/><span>{name}</span><LogOut/></button>:<button className="userBtn" onClick={()=>setAuthOpen(true)}><User/><span>Login</span></button>}<button className="bag" onClick={()=>notify(cart?cart+' item in your cart':'Your cart is empty')}><ShoppingBag/><i>{cart}</i></button></div></header>
 <main><section className="hero"><div><span className="tag"><Sparkles/> AI-POWERED COMMERCE</span><h1>SEE IT.<br/><em>CUSTOMIZE IT.</em><br/>BUY IT.</h1><p>Belanja lebih pintar. Coba fashion secara virtual, buat desain sablonmu sendiri, dan temukan produk favorit dalam satu tempat.</p><div className="cta"><a href="#shop">Explore Shop <ArrowRight/></a><button className="ghost" onClick={()=>setStudio(true)}><Sparkles/> Open Virtual Studio</button></div></div><div className="visual"><div className="person">👤<span>AFTER<br/><small>PROJECT</small></span></div><label>✨ VIRTUAL TRY-ON<br/><b>Ready</b></label></div></section>
 <section id="categories"><div className="title"><span>SHOP YOUR WAY</span><h2>Explore Categories</h2></div><div className="cats">{cats.map(([n,s,I])=><button key={n} onClick={()=>{setCat(n);document.getElementById('shop')?.scrollIntoView()}}><I/><div><b>{n}</b><small>{s}</small></div><strong>›</strong></button>)}</div></section>
 <section className="ai" id="studio"><Sparkles/><div><small>AFTER VIRTUAL STUDIO</small><h2>Your design. Your style. <em>See it before you buy.</em></h2><p>Upload desain, pilih pakaian, dan siapkan preview sebelum Virtual Try-On YouCam.</p></div><button onClick={()=>setStudio(true)}>Open Virtual Studio <ArrowRight/></button></section>
 <section id="shop"><div className="shophead"><div className="title"><span>CURATED FOR YOU</span><h2>Discover Products</h2></div><label className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari produk..."/></label></div><div className="filters">{['All','Fashion','Custom Print','Electronics','Food'].map(x=><button key={x} className={cat===x?'on':''} onClick={()=>setCat(x)}>{x}</button>)}</div><div className="grid">{shown.map((p,i)=><article key={p.name}><div className={'pic p'+i}><span>{p.emoji}</span><i>{p.category==='Fashion'?'VIRTUAL TRY-ON':p.category==='Custom Print'?'CUSTOMIZE':'NEW'}</i></div><div className="info"><small>{p.category}</small><h3>{p.name}</h3><div><b>{p.price}</b><button onClick={()=>p.category==='Fashion'||p.category==='Custom Print'?setStudio(true):add(p)}>+</button></div></div></article>)}</div></section></main>
 <footer><div className="brand"><Sparkles/> AFTER <b>AI</b></div><span>Commerce, reimagined with AI.</span><small>After Project © 2026</small></footer>
 {studio&&<div className="overlay"><div className="modal studioModal"><button className="close" onClick={()=>setStudio(false)}><X/></button><span className="tag"><Sparkles/> AFTER VIRTUAL STUDIO</span><h2>Design it. Wear it. See it.</h2><div className="steps"><b>1 Choose</b><b>2 Upload</b><b>3 Preview</b></div><div className="studioGrid"><div><label>Choose garment</label><div className="garments">{['T-Shirt','Hoodie','Jacket'].map(x=><button className={garment===x?'selected':''} onClick={()=>setGarment(x)}>{x}</button>)}</div><label>Upload your artwork</label><button className="upload" onClick={()=>fileRef.current?.click()}><Upload/> {design?'Change design':'Upload PNG / JPG'}</button><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg" onChange={upload}/><button className="tryBtn" onClick={()=>design?notify('Preview ready — YouCam VTO connection is the next API step'):notify('Upload a design first')}><Sparkles/> Prepare Virtual Try-On</button></div><div className="preview"><div className="shirtPreview">👕{design&&<img src={design} alt="Uploaded design"/>}</div><b>{garment} Preview</b><small>{design?'Artwork positioned on garment':'Upload artwork to start preview'}</small></div></div><p className="powered">Virtual Try-On integration: YouCam API</p></div></div>}
 {authOpen&&!auth&&<div className="overlay"><form className="modal authModal" onSubmit={submitAuth}><button type="button" className="close" onClick={()=>setAuthOpen(false)}><X/></button><div className="modalIcon"><User/></div><small>AFTER AI MEMBER</small><h2>{authMode==='login'?'Welcome back':'Create your account'}</h2><p>Simpan keranjang, desain, dan pengalaman belanjamu.</p>{authMode==='signup'&&<input required placeholder="Nama" value={name} onChange={e=>setName(e.target.value)}/>}<input required type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input required type="password" minLength={4} placeholder="Password"/><button className="primary" type="submit">{authMode==='login'?'Login':'Sign Up'} <ArrowRight/></button><div className="switch">{authMode==='login'?'Belum punya akun?':'Sudah punya akun?'} <button type="button" onClick={()=>setAuthMode(authMode==='login'?'signup':'login')}>{authMode==='login'?'Buat akun':'Login'}</button></div><button type="button" className="later" onClick={()=>setAuthOpen(false)}>Lanjut sebagai tamu</button></form></div>}
 {toast&&<div className="toast"><Check/>{toast}</div>}</>}